-- 코드를 입력하세요
SELECT a. AUTHOR_ID, a. AUTHOR_NAME, b.CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM AUTHOR a 
JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;

