SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE*30*(100-d.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON c.CAR_TYPE = d.CAR_TYPE
WHERE c.CAR_ID not in (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01')
AND d.DURATION_TYPE LIKE '30%'
GROUP BY c.CAR_ID
HAVING c.CAR_TYPE IN ('세단', "SUV") AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
