-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER, 
    COUNT(DISTINCT(u.USER_ID)) AS USERS
FROM USER_INFO u JOIN ONLINE_SALE s
ON u.USER_ID = s.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;