-- 코드를 입력하세요
SELECT h.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS a
RIGHT JOIN (SELECT ROW_NUMBER() OVER (ORDER BY ANIMAL_ID) -1 "HOUR"
           FROM ANIMAL_OUTS
           LIMIT 24) AS h
ON HOUR(DATETIME) = h.HOUR
GROUP BY h.HOUR;

# SET @hour := -1;
# SELECT (@hour := @hour + 1) as HOUR,
# 	(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT 
# FROM ANIMAL_OUTS WHERE @hour < 23;