-- 코드를 입력하세요
SELECT L.ANIMAL_ID, L.NAME
FROM ANIMAL_INS L, ANIMAL_OUTS R
# INNER JOIN ANIMAL_OUTS R
#     ON L.ANIMAL_ID = R.ANIMAL_ID
WHERE L.ANIMAL_ID = R.ANIMAL_ID AND R.DATETIME < L.DATETIME
ORDER BY L.DATETIME